---
engines:
  eslint:
    enabled: true
    channel: eslint-3
  scss-lint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - "**.js"
  - "**.scss"
exclude_paths:
- node_modules/**/*
- test/**/*
- coverage/**/*
- documentation/**/*
- dist/**/*
